# This file was generated by GoReleaser. DO NOT EDIT.
cask "poker" do
  version "1.0.2"

  on_macos do
    on_arm do
      sha256 "bc0edf931a4fd1fc44614a7e4eb9f0b4ce607110650c3c611f84885b4da91b2a"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2fc137a651270a65776025696a25c0639713a88b2835b9ff5f91794a19c7a6fa"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a77b07c8ac8e2e5012cda9ecc1febd66eb527380ccb03e32baf375e1f7fe0c26"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6744e40379fd65b48f8f9635a540327fa15c0efd40313d844ff041a2e236f7fc"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_linux_amd64.tar.gz"
    end
  end

  name "poker"
  desc "CTech Poker — terminal client"
  homepage "https://github.com/artur-oliveira/ctech-poker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poker"]
    end
  end

  # No zap stanza required
end
