# This file was generated by GoReleaser. DO NOT EDIT.
cask "poker" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "aa9f0dae17418780c96e953912e396f1aa6944fb5f712a6978f2c38841deddf3"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "034dd6563b7a0a9a315a7e745388b4692da939258d502966577763322562c701"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ae1bd2e8078a8c70dc812269b04d5bd4c3615559a2736d5fe8577acccd0878eb"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b02659cb69e9930c5473c383554d0b3c0ec2b387706760c8372e1747554c8f9d"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_linux_amd64.tar.gz"
    end
  end

  name "poker"
  desc "CTech Poker — terminal client"
  homepage "https://github.com/artur-oliveira/ctech-poker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poker"]
    end
  end

  # No zap stanza required
end
