# This file was generated by GoReleaser. DO NOT EDIT.
cask "poker" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "219f786c0aa35d54e76fbbf53de11dc703c879826ff8a43aa87c3a08df246d96"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9d6a24856de00f577d057088fa45ac578193cc8641c0aece96a1599ea7f0b478"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8f0d7391c91d0f15d0f4085d48ad91b742c1bf2e1ee967173029d879368bad72"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "13d31c940be798d7720397dd74b95e3570843ffae340f0530a3436afd9308421"
      url "https://github.com/artur-oliveira/ctech-poker/releases/download/v#{version}/poker_#{version}_linux_amd64.tar.gz"
    end
  end

  name "poker"
  desc "CTech Poker — terminal client"
  homepage "https://github.com/artur-oliveira/ctech-poker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/poker"]
    end
  end

  # No zap stanza required
end
